spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liangliang1st/config-repos
          username: liangliang1st@outlook.com
          password: zhimakaimen0604
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
